name: AWS Deployment Workflow

on:
  workflow_dispatch:  # Allow manual trigger from 'productionmain'
    inputs:
      branch:
        description: 'The source branch for deployment'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-south-1

    - name: Request MFA code
      run: |
        echo "Please enter your MFA code"
        read MFA_CODE
        export MFA_CODE=$MFA_CODE
    
    - name: Perform AWS deployment (with MFA)
      run: |
        aws sts get-session-token --serial-number arn:aws:iam::account-id:mfa/your-mfa-device --token-code $MFA_CODE --output json > session.json
        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId session.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey session.json)
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken session.json)
        
        # Now perform the actual deployment (e.g., push to S3, deploy Lambda, etc.)
        echo "Listing Lambda functions in AWS..."
        aws lambda list-functions --output table
