name: AWS Lambda Listing Workflow

on:
  workflow_dispatch:  # Allow manual trigger with inputs for credentials and MFA
    inputs:
      branch:
        description: 'The source branch for deployment'
        required: true
        default: 'main'
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      mfa_code:
        description: 'MFA code from your device'
        required: true

jobs:
  list-lambda-functions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ github.event.inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ github.event.inputs.aws_secret_access_key }}
        aws configure set region us-east-1  # Modify as needed

    - name: Request MFA code (manual input handled through inputs)
      run: |
        MFA_CODE="${{ github.event.inputs.mfa_code }}"
        
        # Debugging: Print the MFA code to ensure it's passed correctly (Do not print in production)
        echo "MFA Code: $MFA_CODE"
        
        # Check if MFA_CODE is empty
        if [ -z "$MFA_CODE" ]; then
          echo "Error: MFA code is not provided or is empty."
          exit 1
        fi
    
    - name: Perform AWS authentication with MFA
      run: |
        MFA_ARN="arn:aws:iam::975049994612:mfa/MS"  # Replace with your actual ARN
        
        # Running the get-session-token command with MFA
        echo "Requesting session token with MFA..."
        aws sts get-session-token --serial-number $MFA_ARN --token-code $MFA_CODE --output json > session.json
        
        # Check if the session was successfully created
        if [ $? -ne 0 ]; then
          echo "Error: Failed to get session token."
          exit 1
        fi
        
        # Parse the session JSON response to get temporary credentials
        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId session.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey session.json)
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken session.json)
    
    - name: List Lambda Functions
      run: |
        echo "Listing Lambda functions in AWS..."
        aws lambda list-functions --output table
