name: AWS Deployment Workflow

on:
  workflow_dispatch:  # Allow manual trigger with inputs for credentials and MFA
    inputs:
      branch:
        description: 'The source branch for deployment'
        required: true
        default: 'main'
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      mfa_code:
        description: 'MFA code from your device'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ github.event.inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ github.event.inputs.aws_secret_access_key }}
        aws configure set region us-east-1

    - name: Request MFA code (manual input handled through inputs)
      run: |
        MFA_CODE=${{ github.event.inputs.mfa_code }}
        echo "Using MFA Code: $MFA_CODE"
    
    - name: Perform AWS deployment (with MFA)
      run: |
        aws sts get-session-token --serial-number arn:aws:iam::account-id:mfa/your-mfa-device --token-code $MFA_CODE --output json > session.json
        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId session.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey session.json)
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken session.json)
        
        # Now perform the actual deployment (e.g., push to S3, deploy Lambda, etc.)
        aws s3 cp ./build s3://your-bucket-name --recursive
